default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: streamingstats_dev
  password:

test:
  <<: *default
  database: streamingstats_test

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>
  username: app
  password: <%= ENV['DATABASE_PASSWORD'] %>
